name: Scoverage Sample Build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Setup Scala
      uses: olafurpg/setup-scala@v10
      with:
        java-version: "openjdk@1.17.0"

    - name: Run Tests
      run: sbt +clean +coverage +test +coverageReport +coveralls
